apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-backend
  namespace: happywiseghala
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-backend
  template:
    metadata:
      labels:
        app: flask-backend
    spec:
      containers:
      - name: flask-backend
        image: marigah/happywiseghala-backend:1.2
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: postgres-config
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_HOST
          value: postgres-service
        - name: ADMIN_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: ADMIN_USERNAME
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: ADMIN_PASSWORD
