apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: happywiseghala
spec:
  selector:
    app: nginx-frontend
  ports:
  - protocol: TCP
    port: 9093
    targetPort: 80
  type: NodePort
